# Generated by Django 3.1.5 on 2021-02-01 03:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.UUID('a6a6eeef-fd4f-44e2-bcbb-5fa86b5c8757'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Checked',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.UUID('3c24989e-a90c-4cbe-a45c-fb28fe202c77'), primary_key=True, serialize=False)),
                ('student_email', models.EmailField(max_length=75, unique=True)),
                ('state', models.CharField(choices=[('SUBMIT', 'Submit'), ('NOT_SUBMIT', 'Not_Submit'), ('LATE_SUBMIT', 'Late_Submit')], default='NOT_SUBMIT', max_length=20)),
                ('homework_name', models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, related_name='homework_name', to='statement.homework')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
