# Generated by Django 3.1.5 on 2021-02-01 03:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checked',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c73944ee-8f98-4daa-8ede-789d93d93dfc'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='homework',
            name='id',
            field=models.UUIDField(default=uuid.UUID('21ad82b9-7fc7-4502-91f2-b68a90fd1f5a'), primary_key=True, serialize=False),
        ),
    ]
