# Generated by Django 3.1.5 on 2021-01-31 15:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checked',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ac9dbb9c-5814-4e84-8c00-83196e1b9b13'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='checked',
            name='state',
            field=models.CharField(choices=[('SUBMIT', 'Submit'), ('NOT_SUBMIT', 'Not_Submit'), ('LATE_SUBMIT', 'Late_Submit')], default='NOT_SUBMIT', max_length=25),
        ),
        migrations.AlterField(
            model_name='homework',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d7342402-bbf8-4621-9ebf-cb47930971d5'), primary_key=True, serialize=False),
        ),
    ]
