# Generated by Django 3.1.5 on 2021-01-31 17:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8b9f9c1d-1b1e-4029-b94f-70a639c17e76'), primary_key=True, serialize=False),
        ),
    ]
