# Generated by Django 3.1.5 on 2021-01-31 15:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0002_auto_20210201_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checked',
            name='homework',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='statement.homework'),
        ),
        migrations.AlterField(
            model_name='checked',
            name='id',
            field=models.UUIDField(default=uuid.UUID('35362019-0381-43d1-9439-7d84ffcb98c0'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='checked',
            name='state',
            field=models.CharField(choices=[('SUBMIT', 'Submit'), ('NOT_SUBMIT', 'Not_Submit'), ('LATE_SUBMIT', 'Late_Submit')], default='NOT_SUBMIT', help_text='과제상태', max_length=25),
        ),
        migrations.AlterField(
            model_name='checked',
            name='student_email',
            field=models.EmailField(help_text='학생이메일', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='id',
            field=models.UUIDField(default=uuid.UUID('23106e7d-e913-4b6a-b2d9-fb52aea6987b'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='homework',
            name='name',
            field=models.CharField(help_text='과제명', max_length=50),
        ),
    ]
