# Generated by Django 3.1.5 on 2021-01-31 15:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0004_auto_20210201_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checked',
            name='homework_name',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='statement.homework'),
        ),
        migrations.AlterField(
            model_name='checked',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6cc2b143-3ea7-4cfe-9715-6046e4bd58b1'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='homework',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9cf6ed29-dda1-4104-99ac-c2b648a726f2'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='homework',
            name='name',
            field=models.CharField(help_text='과제명', max_length=20),
        ),
    ]
