# Generated by Django 3.1.5 on 2021-01-31 15:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0005_auto_20210201_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checked',
            name='homework_name',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='statement.homework'),
        ),
        migrations.AlterField(
            model_name='checked',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fceb70a2-ffeb-46aa-96ac-31e76edf260f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='checked',
            name='student_email',
            field=models.EmailField(help_text='학생이메일', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9b3dd6d3-70d2-4822-a7a1-9b46784ea0c2'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='homework',
            name='name',
            field=models.CharField(help_text='과제명', max_length=50),
        ),
    ]
