# Generated by Django 3.1.5 on 2021-01-31 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0006_auto_20210201_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checked',
            name='id',
            field=models.UUIDField(default=uuid.UUID('18d30dc3-5614-46bf-be39-679b7aa13c8b'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='homework',
            name='id',
            field=models.UUIDField(default=uuid.UUID('81bcbfd1-5871-46b1-a499-57e67a02e44a'), primary_key=True, serialize=False),
        ),
    ]
